apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /nfs/project_inventory_app
    server: 192.168.109.156
