apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8sexec-inventory-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]



